---
# Source: renovate-server/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: renovate-server/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  config.yaml: |
    github:
    - api:
        auth:
          oauth:
            token: <my personal github api token>
        baseURL: https://api.github.com/
        uploadURL: https://uploads.github.com/
      projects: []
      webhook:
        path: /github-com
    gitlab:
    - api:
        auth:
          oauth:
            token: <my personal gitlab api token>
        baseURL: https://gitlab.com/
      projects: []
      webhook:
        path: /gitlab-com
    server:
      executor:
        kubernetes:
          kubeClient:
            fake: false
            rateLimit:
              burst: 10
              enabled: false
              qps: 5
          renovateImage: docker.io/renovate/renovate:latest
          renovateImagePullPolicy: Always
      log:
      - file: stderr
        format: console
        level: verbose
      webhook:
        listen: :8080
---
# Source: renovate-server/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: renovate-server:controller
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - get
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - create
---
# Source: renovate-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
---
# Source: renovate-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: renovate-server
      app.kubernetes.io/instance: renovate-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: renovate-server
        app.kubernetes.io/instance: renovate-server
    spec:
      securityContext:
        {}
      serviceAccountName: renovate-server
      containers:
        - name: renovate-server
          securityContext:
            {}
          image: "docker.io/arhatdev/renovate-server:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
