---
# Source: renovate-server/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: renovate-server/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  config.yaml: Z2l0aHViOiBbXQpnaXRsYWI6IFtdCnNlcnZlcjoKICBleGVjdXRvcjoKICAgIGt1YmVybmV0ZXM6CiAgICAgIGt1YmVDbGllbnQ6CiAgICAgICAgZmFrZTogZmFsc2UKICAgICAgICByYXRlTGltaXQ6CiAgICAgICAgICBidXJzdDogMTAKICAgICAgICAgIGVuYWJsZWQ6IGZhbHNlCiAgICAgICAgICBxcHM6IDUKICAgICAgcmVub3ZhdGVJbWFnZTogZG9ja2VyLmlvL3Jlbm92YXRlL3Jlbm92YXRlOmxhdGVzdAogICAgICByZW5vdmF0ZUltYWdlUHVsbFBvbGljeTogQWx3YXlzCiAgbG9nOgogIC0gZmlsZTogc3RkZXJyCiAgICBmb3JtYXQ6IGNvbnNvbGUKICAgIGxldmVsOiB2ZXJib3NlCiAgd2ViaG9vazoKICAgIGxpc3RlbjogOjgwODA=
---
# Source: renovate-server/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: renovate-server
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - get
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - create
---
# Source: renovate-server/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: renovate-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: renovate-server
subjects:
- kind: ServiceAccount
  name: renovate-server
  namespace: default
---
# Source: renovate-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
---
# Source: renovate-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-server
  labels:
    helm.sh/chart: renovate-server-0.1.0
    app.kubernetes.io/name: renovate-server
    app.kubernetes.io/instance: renovate-server
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: renovate-server
      app.kubernetes.io/instance: renovate-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: renovate-server
        app.kubernetes.io/instance: renovate-server
    spec:
      securityContext:
        {}
      serviceAccountName: renovate-server
      volumes:
        - name: config
          secret:
            secretName: renovate-server
      containers:
        - name: renovate-server
          securityContext:
            {}
          image: "docker.io/arhatdev/renovate-server:latest"
          imagePullPolicy: Always
          command:
            - /renovate-server
            - -c
            - /etc/renovate-server/config.yaml
          volumeMounts:
          - name: config
            mountPath: /etc/renovate-server
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
