name: Build

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"
  push:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    tags:
    - v*

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  build:
    if: contains(github.head_ref, 'deps/') == false
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        # - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 30m
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install dukkha
      run: |-
        mkdir -p "${HOME}/bin"
        echo "${HOME}/bin" >> $GITHUB_PATH

        docker pull ghcr.io/arhat-dev/dukkha:latest
        ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
        docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"

        chmod +x "${HOME}/bin/dukkha"

    - name: Build
      run: |
        dukkha golang local build renovate-server -j $(nproc --all)

    # - name: Package
    #   run: |
    #     make package.renovate-server.linux.all

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

    - name: Build changelog
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1.8.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # TODO: build changelog using convensional changelog
    - name: Create Release
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      env:
        CHANGELOG_SINCE: ${{ steps.build_changelog.outputs.fromTag }}
        CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
        # token is required by github cli (gh)
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dukkha github local release renovate-server
